services:
  - type: web
    name: guftagu-api
    env: docker
    dockerfilePath: ./apps/backend/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: API_PREFIX
        value: api/v1
      - key: APP_URL
        value: https://guftagu-ten.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: memechat
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://guftagu-api.onrender.com/api/v1/auth/google/callback
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 100
